import { UserProfile, Job, Application, Announcement, SkillTest, Referral, MockSlot } from "./types";

export const DEMO_USERS: UserProfile[] = [
  {
    id: "usr_student_1",
    name: "Aditi Rao",
    email: "aditi.rao@college.edu",
    role: "student",
    branch: "Computer Science & Engineering",
    batch: "2023-2027",
    graduationDate: "2027-06-30",
    cgpa: 8.4,
    backlogs: 0,
    skills: ["React", "TypeScript", "Python", "SQL", "Git", "Data Structures", "Tailwind CSS"],
    points: 45,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "usr_passout_1",
    name: "Rahul Verma",
    email: "rahul.verma@alumni.college.edu",
    role: "student",
    branch: "Electronics & Communication",
    batch: "2021-2025",
    graduationDate: "2025-06-30", // ~15 months ago relative to Oct 2026, within 18 months!
    cgpa: 7.4,
    backlogs: 0,
    skills: ["Java", "Spring Boot", "SQL", "C++", "System Design", "AWS", "Docker"],
    points: 60,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "usr_expired_1",
    name: "Siddharth Menon",
    email: "siddharth.m@alumni.college.edu",
    role: "student",
    branch: "Mechanical Engineering",
    batch: "2020-2024",
    graduationDate: "2024-05-15", // >28 months ago relative to Oct 2026 => Expired
    cgpa: 6.9,
    backlogs: 1,
    skills: ["Python", "MATLAB", "AutoCAD", "Excel"],
    points: 20,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "usr_admin_1",
    name: "Dr. K. S. Nair",
    email: "placement.head@college.edu",
    role: "admin",
    branch: "Career Guidance & Placement Unit",
    batch: "Staff",
    graduationDate: "2030-01-01",
    cgpa: 10.0,
    backlogs: 0,
    skills: ["Placement Coordination", "Industry Relations"],
    points: 999,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
  },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: "job_1",
    company: "Google",
    title: "Associate Software Engineer",
    description: "Join Google's core platform engineering team in Bangalore. You will design, build, and deploy large-scale distributed systems impacting billions of users.",
    requiredSkills: ["Data Structures", "Algorithms", "C++", "Python", "System Design", "Distributed Systems"],
    minCgpa: 8.5,
    allowedBranches: ["Computer Science & Engineering", "Information Technology", "Electronics & Communication"],
    maxBacklogs: 0,
    deadline: "2026-10-18T23:59:59Z",
    oppType: "full-time",
    packageStipend: "₹32.5 LPA",
    location: "Bangalore, India",
    campusOnly: true,
    registrationLink: "https://careers.google.com/jobs/results/?q=software%20engineer%20bangalore",
    postedDate: "2026-09-28",
  },
  {
    id: "job_2",
    company: "Goldman Sachs",
    title: "Engineering Analyst (Quantitative & Tech)",
    description: "Build financial engineering tools, algorithmic execution engines, and risk models with global financial scale and ultra-low latency.",
    requiredSkills: ["Java", "Python", "SQL", "Data Structures", "Financial Markets", "Git"],
    minCgpa: 8.0,
    allowedBranches: ["Computer Science & Engineering", "Electronics & Communication", "Electrical Engineering"],
    maxBacklogs: 0,
    deadline: "2026-10-14T23:59:59Z",
    oppType: "full-time",
    packageStipend: "₹24.0 LPA",
    location: "Hyderabad, India",
    campusOnly: false,
    registrationLink: "https://www.goldmansachs.com/careers/students/programs/campus-recruiting.html",
    postedDate: "2026-09-29",
  },
  {
    id: "job_3",
    company: "Cisco Systems",
    title: "Cloud & Network Software Intern (PPO Eligible)",
    description: "Work on cloud networking, telemetry pipelines, and cybersecurity protocols. Fast-track conversion to full-time PPO based on performance.",
    requiredSkills: ["Python", "Networking", "Linux", "Docker", "Git", "REST APIs"],
    minCgpa: 7.5,
    allowedBranches: ["Computer Science & Engineering", "Electronics & Communication"],
    maxBacklogs: 0,
    deadline: "2026-10-08T23:59:59Z", // Closing soon!
    oppType: "internship",
    packageStipend: "₹65,000 / month",
    location: "Bangalore (Hybrid)",
    campusOnly: true,
    registrationLink: "https://jobs.cisco.com/jobs/SearchJobs/?listFilterMode=1",
    postedDate: "2026-09-25",
  },
  {
    id: "job_4",
    company: "TCS Digital",
    title: "Systems Engineer - Digital & Cloud",
    description: "Digital cadence recruitment drive for modern enterprise development, cloud native migrations, and AI applications.",
    requiredSkills: ["Java", "Python", "SQL", "Cloud Concepts", "Agile"],
    minCgpa: 7.0,
    allowedBranches: ["All"],
    maxBacklogs: 1,
    deadline: "2026-10-25T23:59:59Z",
    oppType: "full-time",
    packageStipend: "₹7.5 LPA",
    location: "Pan-India",
    campusOnly: false,
    registrationLink: "https://nextstep.tcs.com/campus/#/digital-cadence",
    postedDate: "2026-09-30",
  },
  {
    id: "job_5",
    company: "Zoho Corporation",
    title: "Member Technical Staff (Off-Campus Drive)",
    description: "Zoho is actively hiring both 2026 graduates and recent passouts (2024-2025) for full stack product engineering across Chennai and Tenkasi campuses.",
    requiredSkills: ["Java", "C++", "Data Structures", "SQL", "JavaScript"],
    minCgpa: 6.5,
    allowedBranches: ["All"],
    maxBacklogs: 2,
    deadline: "2026-10-30T23:59:59Z",
    oppType: "off-campus",
    packageStipend: "₹8.5 LPA",
    location: "Chennai / Tenkasi",
    campusOnly: false,
    registrationLink: "https://www.zoho.com/careers/jobdetails/?job_id=457313000000000",
    postedDate: "2026-09-27",
  },
  {
    id: "job_6",
    company: "Microsoft",
    title: "Azure Cloud Engineering Intern",
    description: "Collaborate with Azure engineering teams to design resilient microservices and cloud automation infrastructure.",
    requiredSkills: ["C#", "Python", "Azure", "Docker", "Kubernetes", "Data Structures"],
    minCgpa: 8.2,
    allowedBranches: ["Computer Science & Engineering", "Electronics & Communication"],
    maxBacklogs: 0,
    deadline: "2026-10-12T23:59:59Z",
    oppType: "ppo",
    packageStipend: "₹80,000 / month",
    location: "Hyderabad, India",
    campusOnly: true,
    registrationLink: "https://careers.microsoft.com/us/en/job/1789230/Intern-Software-Engineering",
    postedDate: "2026-09-26",
  },
];

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: "app_1",
    jobId: "job_2",
    studentId: "usr_student_1",
    studentName: "Aditi Rao",
    studentBranch: "Computer Science & Engineering",
    studentCgpa: 8.4,
    status: "Shortlisted",
    matchScore: 67,
    appliedAt: "2026-09-30T10:15:00Z",
    company: "Goldman Sachs",
    jobTitle: "Engineering Analyst (Quantitative & Tech)",
    notes: "Aptitude round cleared. Technical interview scheduled.",
  },
  {
    id: "app_2",
    jobId: "job_3",
    studentId: "usr_student_1",
    studentName: "Aditi Rao",
    studentBranch: "Computer Science & Engineering",
    studentCgpa: 8.4,
    status: "Applied",
    matchScore: 67,
    appliedAt: "2026-10-01T08:30:00Z",
    company: "Cisco Systems",
    jobTitle: "Cloud & Network Software Intern",
    notes: "Application under CGPU review.",
  },
  {
    id: "app_3",
    jobId: "job_4",
    studentId: "usr_passout_1",
    studentName: "Rahul Verma",
    studentBranch: "Electronics & Communication",
    studentCgpa: 7.4,
    status: "Interview",
    matchScore: 80,
    appliedAt: "2026-09-28T14:20:00Z",
    company: "TCS Digital",
    jobTitle: "Systems Engineer - Digital & Cloud",
    notes: "Technical & Managerial round scheduled for Oct 5.",
  },
  {
    id: "app_4",
    jobId: "job_5",
    studentId: "usr_passout_1",
    studentName: "Rahul Verma",
    studentBranch: "Electronics & Communication",
    studentCgpa: 7.4,
    status: "Selected",
    matchScore: 80,
    appliedAt: "2026-09-20T11:00:00Z",
    company: "Zoho Corporation",
    jobTitle: "Member Technical Staff",
    notes: "Offer letter issued! CTC: 8.5 LPA.",
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "anc_1",
    title: "Cisco Registration Closes Tomorrow 5:00 PM!",
    body: "All eligible CSE and ECE students must complete their registration and upload verified grade sheets. No extensions will be granted by the corporate team.",
    createdAt: "2026-10-01T09:00:00Z",
    tag: "Urgent",
    author: "CGPU Admin",
  },
  {
    id: "anc_2",
    title: "Google Technical Screening Test Pattern & Guidelines",
    body: "The test will comprise 3 algorithmic questions on LeetCode/HackerRank format. Students are advised to take the Plyace Core System Test to practice before Friday.",
    createdAt: "2026-09-30T16:00:00Z",
    tag: "Drive",
    author: "CGPU Technical Cell",
  },
  {
    id: "anc_3",
    title: "Free Resume Clinic & ATS Optimization Workshop",
    body: "Join our alumni mentors on Zoom this Thursday at 6:30 PM. We will demonstrate how to score above 85% on Plyace ATS checker and tailor your project bullets.",
    createdAt: "2026-09-29T11:30:00Z",
    tag: "Preparation",
    author: "Career Development Cell",
  },
  {
    id: "anc_4",
    title: "Zoho Off-Campus Drive Open for Passed-Out Students",
    body: "Passouts from batches 2024 and 2025 are encouraged to apply directly through the Plyace referral board. 45 interview slots reserved for college alumni.",
    createdAt: "2026-09-27T10:00:00Z",
    tag: "Drive",
    author: "Alumni Relations & CGPU",
  },
];

export const INITIAL_TESTS: SkillTest[] = [
  {
    id: "test_aptitude",
    title: "Campus Quantitative & Logical Reasoning Exam",
    category: "Aptitude",
    durationMin: 10,
    description: "Evaluates speed math, permutations, probability, logical deduction, and verbal analysis standard for Tier-1 corporate screening rounds.",
    totalMarks: 30,
    questions: [
      {
        id: "q_apt_1",
        text: "A train running at 54 km/hr crosses an 180 m long bridge in 20 seconds. What is the length of the train?",
        options: ["120 m", "100 m", "140 m", "150 m"],
        correctIndex: 0, // 54 * 5/18 = 15 m/s. Total distance = 15*20 = 300 m. Train = 300 - 180 = 120 m.
      },
      {
        id: "q_apt_2",
        text: "In how many different ways can the letters of the word 'CORPORATION' be arranged so that the vowels always come together?",
        options: ["50,400", "72,000", "43,200", "14,400"],
        correctIndex: 0,
      },
      {
        id: "q_apt_3",
        text: "A and B can do a piece of work in 12 days and 16 days respectively. If they work on alternate days starting with A, in how many days will the work finish?",
        options: ["13.75 days", "14 days", "13.25 days", "12.5 days"],
        correctIndex: 0,
      },
      {
        id: "q_apt_4",
        text: "Find the odd one out in the series: 3, 5, 11, 14, 17, 21",
        options: ["14", "21", "11", "17"],
        correctIndex: 0,
      },
      {
        id: "q_apt_5",
        text: "If 'P @ Q' means P is mother of Q, 'P # Q' means P is father of Q, and 'P $ Q' means P is sister of Q, what does 'A # B $ C @ D' mean?",
        options: ["A is maternal grandfather of D", "A is paternal grandfather of D", "A is uncle of D", "A is brother of D"],
        correctIndex: 0,
      },
      {
        id: "q_apt_6",
        text: "What is the probability of getting a sum of 9 when two fair dice are thrown simultaneously?",
        options: ["1/9", "1/6", "1/12", "5/36"],
        correctIndex: 0, // (3,6),(4,5),(5,4),(6,3) = 4/36 = 1/9
      },
    ],
  },
  {
    id: "test_tech",
    title: "Core Software Engineering & System Architecture",
    category: "Technical",
    durationMin: 12,
    description: "Evaluates operating systems, concurrency, memory models, database normalization, SQL indexing, and algorithms for product development roles.",
    totalMarks: 30,
    questions: [
      {
        id: "q_tech_1",
        text: "Which of the following database isolation levels prevents phantom reads?",
        options: ["Serializable", "Repeatable Read", "Read Committed", "Read Uncommitted"],
        correctIndex: 0,
      },
      {
        id: "q_tech_2",
        text: "What is the worst-case time complexity of searching in an AVL tree with n nodes?",
        options: ["O(log n)", "O(n)", "O(n log n)", "O(1)"],
        correctIndex: 0,
      },
      {
        id: "q_tech_3",
        text: "In TCP networking, what is the primary role of the SYN-ACK exchange?",
        options: ["Establish sequence numbers and socket connection synchronization", "Verify DNS hostname resolution", "Encrypt TLS payload data", "Negotiate maximum bandwidth throttling"],
        correctIndex: 0,
      },
      {
        id: "q_tech_4",
        text: "Which scheduling algorithm can cause process starvation if higher priority tasks continuously arrive?",
        options: ["Preemptive Priority Scheduling", "Round Robin", "First Come First Served (FCFS)", "Fair Share Scheduler"],
        correctIndex: 0,
      },
      {
        id: "q_tech_5",
        text: "What data structure does a B+ Tree use for internal nodes vs leaf nodes?",
        options: ["Internal nodes store keys for navigation; leaf nodes store actual records or pointers in a linked sequence", "All nodes store duplicate leaf records", "Leaf nodes are binary heaps", "Internal nodes store raw file byte offsets"],
        correctIndex: 0,
      },
      {
        id: "q_tech_6",
        text: "In React, why should state not be mutated directly (e.g. state.push(item))?",
        options: ["Direct mutation bypasses React's virtual DOM reconciliation and shallow equality comparison", "It causes immediate browser memory segmentation fault", "JavaScript arrays are strictly immutable by default", "It blocks CSS repaint execution"],
        correctIndex: 0,
      },
    ],
  },
];

export const INITIAL_REFERRALS: Referral[] = [
  {
    id: "ref_1",
    alumniName: "Ananya Sharma",
    batch: "2023",
    company: "Amazon",
    role: "Software Development Engineer I (AWS DynamoDB)",
    slots: 5,
    location: "Bangalore",
    skillsNeeded: ["Java", "Distributed Systems", "Data Structures"],
    requestsCount: 2,
  },
  {
    id: "ref_2",
    alumniName: "Venkatesh Iyer",
    batch: "2022",
    company: "Uber",
    role: "Backend Engineer II (Core Mobility)",
    slots: 3,
    location: "Hyderabad",
    skillsNeeded: ["Go", "Kafka", "PostgreSQL", "Microservices"],
    requestsCount: 1,
  },
  {
    id: "ref_3",
    alumniName: "Preethi Sundaram",
    batch: "2024",
    company: "Microsoft",
    role: "Software Engineer (M365 Cloud)",
    slots: 4,
    location: "Hyderabad",
    skillsNeeded: ["C#", "Azure", "TypeScript", "React"],
    requestsCount: 3,
  },
];

export const INITIAL_MOCK_SLOTS: MockSlot[] = [
  {
    id: "slot_1",
    hostName: "Karthik Raja (Senior SDE @ Oracle)",
    hostRole: "Alumni Mentor - Batch 2020",
    hostCompany: "Oracle OCI",
    type: "Mock Interview",
    topic: "System Design & Low-Level Architecture Round (1:1)",
    startsAt: "2026-10-04T15:00:00Z",
    capacity: 4,
    bookedCount: 2,
  },
  {
    id: "slot_2",
    hostName: "Meera Krishnan (Tech Lead @ PhonePe)",
    hostRole: "Alumni Mentor - Batch 2021",
    hostCompany: "PhonePe",
    type: "Group Discussion",
    topic: "FinTech Disruptions, UPI Globalization & AI Ethics GD Simulation",
    startsAt: "2026-10-06T17:30:00Z",
    capacity: 8,
    bookedCount: 5,
  },
  {
    id: "slot_3",
    hostName: "Arjun Nambiar (SWE @ Atlassian)",
    hostRole: "Alumni Mentor - Batch 2023",
    hostCompany: "Atlassian",
    type: "Mock Interview",
    topic: "Data Structures, Dynamic Programming & Tree Traversal Live Coding (1:1)",
    startsAt: "2026-10-08T18:00:00Z",
    capacity: 3,
    bookedCount: 1,
  },
];
